### ISSUE TITLE
Prepare first major release

### ISSUE THREAD

**Issue by JuliusWelzel** [neurogeriatricskiel/NGMT#50]
Hi,

in some issues, we keep mentioning tasks to do before the first major release (0.1.0). I would like to collect these in an issue to better work through them. Feel free to add if anything is missing.

- [x] Finish [algorithms](https://github.com/neurogeriatricskiel/NGMT/issues/28) (Pham)
- [x] Brush up examples
- [x] Finalise NGMT dataclass in line with BIDS ([info](https://github.com/neurogeriatricskiel/NGMT/issues/49), ...)
- [x] [Export events](https://github.com/neurogeriatricskiel/NGMT/issues/34) in BIDS style
- [x] [Create changelog](https://github.com/neurogeriatricskiel/NGMT/issues/47)

**Comment by masoudabedinifar** [comment]
Examples and docs brushed up in commit: c5d6af00ba4d743c335f0062e77e71acd19f57a2
